"""FakeProvider: deterministic offline provider for tests and demos.

Given the same prompt it always returns the same text, so tests are reproducible
and the committed demo cache in ``cache/ci/`` can be regenerated byte-for-byte.

Two modes:

- ``responses``: a dict mapping an exact prompt (or a substring, if
  ``match="substring"``) to the reply text.
- ``fn``: a callable ``(prompt, model, params) -> str`` for programmatic replies.

If neither matches, it echoes a short hash of the prompt so the output is still
deterministic but obviously wrong, which is what you want in a test.
"""

from __future__ import annotations

import hashlib
from collections.abc import Callable
from typing import Any

from promptci.providers.base import Completion


class FakeProvider:
    name = "fake"

    def __init__(
        self,
        responses: dict[str, str] | None = None,
        fn: Callable[[str, str, dict[str, Any]], str] | None = None,
        *,
        match: str = "exact",
        latency_ms: float = 1.0,
    ):
        if match not in ("exact", "substring"):
            raise ValueError("match must be 'exact' or 'substring'")
        self.responses = responses or {}
        self.fn = fn
        self.match = match
        self.latency_ms = latency_ms
        self.calls: list[tuple[str, str, dict[str, Any]]] = []

    def _lookup(self, prompt: str, model: str, params: dict[str, Any]) -> str:
        if self.fn is not None:
            return self.fn(prompt, model, params)
        if self.match == "exact":
            if prompt in self.responses:
                return self.responses[prompt]
        else:
            for needle, reply in self.responses.items():
                if needle in prompt:
                    return reply
        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]
        return f"[fake:{digest}]"

    async def complete(self, prompt: str, model: str, **params: Any) -> Completion:
        self.calls.append((prompt, model, dict(params)))
        text = self._lookup(prompt, model, params)
        return Completion(
            text=text,
            prompt_tokens=max(1, len(prompt) // 4),
            completion_tokens=max(1, len(text) // 4),
            latency_ms=self.latency_ms,
            cost_usd=0.0,
            raw={"provider": "fake", "model": model},
        )
